sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - demo
  
jobs:
  include:
    - stage: Mom-Frontend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mom_frontend_flowz:$TRAVIS_BRANCH --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="AWS_SECRETKEY" ./client/
      - docker images
      - docker tag mom_frontend_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/mom_frontend_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/mom_frontend_flowz:$TRAVIS_BRANCH

    





