sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  
jobs:
  include:
    - stage: Mom-Frontend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mom_frontend_flowz:dev --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="AWS_SECRETKEY" ./client/
      - docker images
      - docker tag mom_frontend_flowz:dev $DOCKER_USERNAME/mom_frontend_flowz:dev
      - docker push $DOCKER_USERNAME/mom_frontend_flowz:dev

    





